name: Build

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - "**"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v6

      - name: Maven Build
        run: mvn install

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vprofile-app
          path: target/*.war

  Testing:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Code checkout
        uses: actions/checkout@v6

      - name: Run tests on main branch
        if: github.ref == 'refs/heads/main'
        run: mvn test

      - name: Skip tests on other branches
        if: github.ref != 'refs/heads/main'
        run: echo "Skipping unit tests & code analysis"

      - name: Checkstyle
        if: github.ref == 'refs/heads/main'
        run: mvn checkstyle:checkstyle

      - name: Notify if testing fails
        if: failure()
        run: echo "Testing failed! Please check the logs for details."

  SecurityScan:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Code checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          format: json
          exit-code: 0
          vuln-type: os,library
          output: trivy-report.json

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: trivy-report.json
    
  BUILD_AND_PUBLISH:
    name: BUILD_AND_PUBLISH
    runs-on: ubuntu-latest
    environment: production
    needs: [Build, Testing, SecurityScan]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Code checkout
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}

        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Docker-files/app/multistage/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo *image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG >> $GITHUB_ENV